
name: pull-request-ci
on:
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16' # or specify your preferred version

      - name: Install dependencies
        run: npm ci # Using npm ci for CI environments

      - name: Run tests
        run: npm run tests

  changeset_checks:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - name: Check changeset
        run: npm run changeset:status
